import type { CountyData } from './types';
import generated from '@/data/counties_generated.json';

/**
 * County data, generated by scripts/build_database.py from real Census/BLS/Opportunity
 * Atlas sources. The seed file shipped in the repo contains curated estimates for
 * ~50 representative counties so the app works out-of-the-box; running the pipeline
 * overwrites data/counties_generated.json with the full ~800 county database.
 */
export const COUNTIES: CountyData[] = generated as CountyData[];
